# Generated by Django 5.0.7 on 2024-07-16 09:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='task',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
