# Generated by Django 5.0.7 on 2024-08-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_ticket_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettemplate',
            name='template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
