# Generated by Django 5.0.7 on 2024-08-06 12:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_tickettemplate_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
